version: 1
disable_existing_loggers: true
formatters:
  standard:
    format: '%(asctime)s - %(levelname)-6s - %(module)-10s - %(funcName)-15s - %(lineno)4d: %(message)s'
#               hour    - WARNING/INFO/ETC - name of file - function name - line in file - message
  reduced: 
    format: '%(levelname)-8s - %(module)-15s - %(funcName)-20s - %(lineno)4d: %(message)s'
handlers:
  console:
    level: 'DEBUG'
    class: 'logging.StreamHandler'
    formatter: 'reduced'
    stream : 'ext://sys.stdout'
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    mode: w
#  smtp:
#    level: 'ERROR'
#    class: 'logging.handlers.SMTPHandler'
#    formatter: 'multi_line'
#    mailhost:
#      - '127.0.0.1'
#      - 60025
#    subject: 'Something went wrong'
#    fromaddr: 'sender@example.com'
#    toaddrs:
#      - 'recipient@example.com'
loggers:
  generic:
    level: 'DEBUG'
    handlers:
      - 'console'
      - 'file_handler'
  #    - 'smtp'